[versions]
minSdk = "28"
targetSdk = "33"
compileSdk = "34"
koin-bom = "3.5.3"

[libraries]
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }

[plugins]


[bundles]